---
# Join msg
msg: "§cWelcome to the server."
# Form settings
title: "Staff"
content: "§4Owners: §fMarioTN04,KenoZeu\n§aAdmin: §fxRaulGaming180x\n§bMod: §fqKoppe\n§2Helper: §fEdyGamerRo\n§7plugin made by xAndrei52 :)" 
button: "I undestand okk"
...
